### ISSUE TITLE
Javascript Tutorial seems to be designed to run only on Linux

### ISSUE THREAD

**Issue by chanezon** [metaparticle-io/metaparticle-ast#2]
https://metaparticle.io/tutorials/javascript/
I installed mp-compiler-darwin on my Mac, with Docker for Mac and tried the first tutorial.

```
npm start
npm start

> metaparticle-example@0.0.1 start /package/tutorials/javascript
> node ./index.js

fs.js:549
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open '/proc/1/cgroup'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.fs.readFileSync (fs.js:397:15)

```

I guess the example is designed to run on a Linux system.

**Comment by brendandburns** [comment]
I believe this is now fixed. (by you :) please feel free to re-open if this isn't true.

**Comment by chanezon** [comment]
yes, sorry I opened the original issue on the wrong project. It's fixed now.
