### ISSUE TITLE
mp-compiler-linux-amd64.tgz release v0.4.0 appears to contain darwin binaries

### ISSUE THREAD

**Issue by DazWilkin** [metaparticle-io/metaparticle-ast#8]
https://github.com/metaparticle-io/metaparticle-ast/releases/tag/v0.4.0

`mp-compiler-linux-amd64.tgz` contains `mp-compiler-darwin-amd64` (darwin)

This is not an incorrectly named `linux-amd64` file but the incorrect file.

`mp-compiler-darwin-amd64.tgz` contains `mp-compiler-darwin-amd64`

Built a linux-amd64 compiler for my own purposes but recommend correcting the releases.

**Comment by cdhunt** [comment]
The Windows artifact also appears to actually be a gzip of a non-Windows binary.

**Comment by brendandburns** [comment]
ugh! I'll see what happened...

**Comment by brendandburns** [comment]
Ok, the files should now be fixed, apologies for the delay...
